import { randomBytes } from "node:crypto";

export function validateProjectName(name: string): string | undefined {
  if (!name) return "Project name is required";
  if (!/^[a-z0-9][a-z0-9-]*$/.test(name)) {
    return "Use lowercase letters, numbers and dashes (must start with a letter or number)";
  }
  if (name.length > 100) return "Name too long";
  return undefined;
}

export function generateEnvFiles(opts: { databaseUrl?: string }): {
  path: string;
  content: string;
}[] {
  const secret = randomBytes(32).toString("base64url");
  const apiLines = [
    "# Generated by create-baro",
    "PORT=8000",
    "WEB_ORIGIN=http://localhost:3000",
    `BETTER_AUTH_SECRET=${secret}`,
    "BETTER_AUTH_URL=http://localhost:8000",
  ];
  if (opts.databaseUrl) {
    apiLines.push(`DATABASE_URL=${opts.databaseUrl}`);
  }
  return [
    { path: "apps/api/.env", content: `${apiLines.join("\n")}\n` },
    {
      path: "apps/web/.env.local",
      content: "NEXT_PUBLIC_API_URL=http://localhost:8000\n",
    },
  ];
}

/** Paths removed from the downloaded template — internal tooling and docs. */
export const SANITIZE_PATHS = [
  ".git",
  "docs/superpowers",
  ".superpowers",
  "tooling",
  ".claude",
  ".agents",
  ".windsurf",
  "skills-lock.json",
];

export function renameRootPackage(jsonText: string, name: string): string {
  const pkg = JSON.parse(jsonText);
  pkg.name = name;
  return `${JSON.stringify(pkg, null, 2)}\n`;
}
